### ISSUE TITLE
User and password are not filled in on Jellyfin

### ISSUE THREAD

**Issue by stroobandt** [alandmoore/admbrowser#20]
The user and password are not automatically filled in —like other browsers with password management do— on the [Jellyfin](https://Jellfin.org) media system.

This can be tested with the following demo YAML file:

```yaml
default_password: ''
default_user: demo
navigation: False
start_url: https://demo.jellyfin.org/stable/web/index.html
window_size: max
```

This would be nice to have for a kiosk browser without keyboard.
