### ISSUE TITLE
CSS overwrite statements in .yaml file

### ISSUE THREAD

**Issue by stroobandt** [alandmoore/admbrowser#28]
This is an idea that originates from the [`surf`](https://surf.suckless.org) browser. Suckless.org's `surf` is a small WebKit2/GTK+ based browser that I used to use quite often before encountering this great WebEngine/PyQt5 ADMBrowser.

`surf` allows to write a couple of CSS statements that will overwrite some of the CSS of a known web site. This results to be a handy way to eleminate ads and other annoyances or rather to emphasise parts of a web page one is interested in.

Here is an actual example for some of the named CSS classes of the domain `rtl.fr`:
```css
.ads, .legal-notice, .newsletter, .produit {display: none !important;}
.hResultPrincipal {font-size: 175% !important;}
```

CSS overwrite statements would be a great and natural addition to ADMBrowser's `.yaml` site-dependent configuration files. It would also solve the issue of ADMBrowser users currently being exposed to ads that could be perceived as offensive in an educational or public library setting.
